#!/bin/bash

set -e

${top_builddir}/bin/mgwport-inplace --help
echo

${top_builddir}/bin/mgwport-inplace --version
echo

cat > foo-1.2.3-4.mgwport <<-_EOF
	DESCRIPTION="mgwport messages test package"
	HOMEPAGE="http://mingw.org/mgwport/"
	SRC_URI="http://mingw.org/mgwport/\${P}.ABC"
	PKG_COMPTYPES="bin doc lic"
	_EOF

${top_builddir}/bin/mgwport-inplace foo-1.2.3-4.mgwport info
echo

rm -f foo-1.2.3-4.mgwport
